apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    type: frontend
spec:
  replicas: 2
  selectors:
    matchLabels:
      type: frontend
  template: 
    metadata:
      name: nginx-pod
      labels:
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
